### ISSUE TITLE
Error: AudioConverterFillComplexBuffer failed

### ISSUE THREAD

**Issue by rfoa** [muhku/FreeStreamer#227]
Hi! In the log is printed thousands of times the following message:
`[audio_stream.cpp:1433 thread 8e03] AudioConverterFillComplexBuffer failed, error -50`

The error happens after the multitask screen opens (Double-click the Home button)... Immediately the audio is muted / stopped, but no notification is received by onStateChange, onFailure or onMetaDataAvailable
But when it goes to the home screen (One-click the Home button), this error does not happen.

The error also happens when switching from 3G to Wi-Fi while running streaming (isPlaying = true)

More Info:
* I tested in live streaming
* The error happens in both MP3 and AAC streamings
* Error in a real devices: iPhone 5C 8.3, iPhone 6 8.2 .... Working normally in the Simulator
* This happened after upgrade from version 2.14.1 to version 3.0.3

Thanks!

**Comment by muhku** [comment]
Thanks for reporting. This sounds like an iOS "feature" when doing backgrounding. Do the errors stop coming up when you get back to the app? Or audio never comes back even when you get back to the app in foreground mode?

**Comment by muhku** [comment]
Noticed another bug that we might be actually busy looping in case of decoder errors... commit e819afe62fb1d4d79c508174176c87cd67a7f78d

Pushed 3.0.4. Let me know if still problems with that.

**Comment by rfoa** [comment]
> Do the errors stop coming up when you get back to the app? Or audio never comes back even when you get back to the app in foreground mode?

No, audio never comes back. 
I Put logs in the functions of the AppDelegate ... the error occurs after the call of applicationWillResignActive and applicationDidBecomeActive

**Comment by muhku** [comment]
OK. This means that after kAudio_ParamError (-50) the stream needs to raise an error. I will take a look into it what would be an appropriate error.

**Comment by rfoa** [comment]
> Pushed 3.0.4. Let me know if still problems with that.

Yes, still continues ...
But now is called didReceiveMemoryWarning function of my ViewController and soon after the application is terminated/crashed due to memory error: 
`Message from debugger: Terminated due to Memory Error`

This new error also occurs randomly, about 1 or 2 minutes after the player has been started

**Comment by muhku** [comment]
Pushed cd26996b7d400c141ba59c5408545f5c81197111 If the -50 error comes, decoder is stopped and the kFsAudioStreamErrorTerminated is raised. You must restart the stream to recover from this. Does it help?

**Comment by muhku** [comment]
Pushed the changes in 3.0.5.

**Comment by rfoa** [comment]
Thank you, this change helps catch this kind error. The kFsAudioStreamErrorTerminated was called at random. I could not find a pattern for it.

But still having memory failures!
No matter if the app is in the background and foreground, the error always happens. And only get the message in the log: `Received memory warning`

This type of error does not happen in version 2.14.3. Only in current versions (3.0.4 and 3.0.5).

**Comment by rfoa** [comment]
More info:
Debug Navigator
7.1 mb
350 mb 750 mb

**Comment by rfoa** [comment]
More Info:
* Just before the application crashed, the memory usage rises 7.1 MB (standard) to 350 MB and 750 MB finally (checked by Xcode Debug Navigator) ... Its maybe a decoder memory leak?
* I realized that happens close to onMetaDataAvailable fetch events (start or end of songs)

**Comment by muhku** [comment]
Can the memory leak reproduced on Simulator or device only?
Does the demo app also leak memory in the same way?

It seems that Xcode shows stable memory usage on Simulator so that's why a way to reproduce this is needed.

**Comment by rfoa** [comment]
I enabled AS_DEBUG in audio_stream.cpp and will upload here my log file since starting the player until the memory error message / app crash. I hope it helps.
The memory error also occurs in FreeStreamerMobile demonstration project with any streaming.
The simulator can not reproduce the error. The error occurs only on real devices

**Comment by rfoa** [comment]
In the logs, i also prints messages in the events of the player, the AppDelegate and ViewController

1. In this log, I Double-click the Home button for the error happen faster.
[log_memory_error_1.txt](https://github.com/muhku/FreeStreamer/files/51331/log_memory_error_1.txt)

2. In this log, just started the player. In this case the error happens randomly. 
[log_memory_error_2.txt](https://github.com/muhku/FreeStreamer/files/51340/log_memory_error_2.txt)

**Comment by muhku** [comment]
Thanks for the logs.
My theory is that using pthread_cond_wait() in encoderDataCallback on device is bad. So I partly reverted back to the 2.9.x implementation. Commit d3135d01f31abae296ccd8827ea5da192efdbff5

With this, 1) Does it still leak? 2) Any stutters or otherwise weird behavior?

**Comment by rfoa** [comment]
> 1) Does it still leak?

Apparently not. But I am doing more extensive testing

> 2) Any stutters or otherwise weird behavior?

Yes... After a while the audio becomes muted. Instead of leaking memory, the player is muted. I will some logs about it.

Other question: Is it normal to be called XYZ continuously when the player is stopped?

**Comment by rfoa** [comment]
Instead of crash app, the player goes mute.
I noticed that almost every moment is called `[audio_stream.cpp:1716 thread 9003] encoderDataCallback called` after the player be muted...

[log_memory_error_with_player_muted_1.txt](https://github.com/muhku/FreeStreamer/files/51394/log_memory_error_with_player_muted_1.txt)

**Comment by muhku** [comment]
You are right, AudioConverterFillComplexBuffer should not be called when the player is stopped. However, the decoder thread should run continuously and the state checks should skip conversion when it is not needed. The "calling AudioConverterFillComplexBuffer" debug message was in a wrong place so it shows up in the logs even though it was not really called.

The muting happens if the audio converter runs out of data and it is not restarted. I think there was a race condition and the converter was not properly restarted. The logic should be now on par with 2.9.x (added commit a9ddc11e34b252c1a702494c6a699ee5f9671c8e). I would be grateful for a new run of logs, if you still manage to reproduce this. Thanks!

**Comment by muhku** [comment]
3.0.6 pushed with all the changes so far.

**Comment by rfoa** [comment]
Ok, I see what happened. I will now check the version 3.0.6
I thank you for your attention

**Comment by rfoa** [comment]
Unfortunately the problem still continues ... but it seems occurs less frequently.
* No memory leak
* No crash of app
* The player is still becoming muted after a random time
* Occurs like a "loop" in audio_stream.cpp until the player be stopped:
````
[audio_stream.cpp:1728 thread 9103] encoderDataCallback called
[audio_stream.cpp:1392 thread 9103] decoder: run out of data, restarting the audio converter
[audio_stream.cpp:960 thread 807] streamHasBytesAvailable: 1024 bytes
[audio_stream.cpp:1900 thread 807] streamDataCallback: inNumberBytes 875, inNumberPackets 3
[audio_stream.cpp:1573 thread 807] Converter run out of data: more data available
[audio_stream.cpp:1674 thread 807] Cache cleanup called but no free packets
[audio_stream.cpp:960 thread 807] streamHasBytesAvailable: 116 bytes
[audio_stream.cpp:1900 thread 807] streamDataCallback: inNumberBytes 265, inNumberPackets 1
[audio_stream.cpp:1674 thread 807] Cache cleanup called but no free packets
[audio_stream.cpp:1365 thread 9103] calling AudioConverterFillComplexBuffer
````

Full log: [log_player_muted_1.txt](https://github.com/muhku/FreeStreamer/files/52302/log_player_muted_1.txt)

**Comment by rfoa** [comment]
I noticed that the audio is muted close to when this event happens: 
`[audio_stream.cpp:1392 thread 9103] decoder: run out of data, restarting the audio converter`

**Comment by muhku** [comment]
Seems that it is possible for the decoder and the cache cleanup enter into a race condition. The last two commits attempt to fix that. Changes in 3.0.7.

**Comment by rfoa** [comment]
Hello again. Unfortunately the problem still continues in versions 3.0.7, 3.0.8 and commit 990b534.

I can not detect "what" that triggers the problem, but I detected something new: from the moment the audio is muted, there is a small increase in memory usage (about 50kb per second) until the app automatically be closed. New memory leak?

New logs:
* 3.0.7: [log_memory_error_with_player_muted_2.txt](https://github.com/muhku/FreeStreamer/files/53907/log_memory_error_with_player_muted_2.txt)

* 3.0.8: [log_memory_error_with_player_muted_3.txt](https://github.com/muhku/FreeStreamer/files/53929/log_memory_error_with_player_muted_3.txt)


I thank you for your time spent to try to correct this problem. Your lib is very good!

**Comment by muhku** [comment]
There's something really really odd going on in the logs when the "looping" starts when audio is muted. I need to take a better look. As a quick observation I noticed that I forgot to invalidate the decode timer when the runloop exits. That was fixed. Also I removed the looping when decoding packets, now we only run as per the 40ms timer interval.

**Comment by muhku** [comment]
OK, from what I can tell, there still was a possibility with a race condition with the cache cleanup, as it was called from the main thread and the decoder thread. I simplified this so that the cache cleanup is only called from the decoder thread.

**Comment by rfoa** [comment]
Sorry for the delay to check...
The 3.0.9 version still does not work. Same problems.

I noticed that now the audio is muted after printing the message: `Queue can not accept packets, return`

The error could be occurring in Audio_Queue class?
If following the stacktrace of the message, we have:
1. `m_queueCanAcceptPackets = false` in `Audio_Stream::enqueueCachedData()`
2. Some function called `audioQueueOverflow()` to set false in `m_queueCanAcceptPackets`
3. I noticed that `audioQueueOverflow()` is called only by `Audio_Queue::enqueueBuffer()`

* The functions `Audio_Queue::handlePacket()`, `Audio_Queue::enqueueBuffer()` and  `Audio_Queue::enqueueCachedData()` could be related to the problem?

* It would be good to take a check why this message is printed: (it's only printed after the player be muted)
 `[audio_queue.cpp:413 thread 807] int astreamer::Audio_Queue::handlePacket(const void *, AudioStreamPacketDescription *): skipped enqueueBuffer AQ_BUFSIZ - m_bytesFilled 8192, packetSize 8192`

Full log: [log_player_error_3.0.9.txt](https://github.com/muhku/FreeStreamer/files/55819/log_player_error_3.0.9.txt)

Once again thank you

**Comment by muhku** [comment]
Thanks for very nice findings. It looks like Audio_Stream is behaving a lot more sanely now but like you said, Audio_Queue state seems to corrupt. The difference to 2.9.x is that Audio_Queue is driven both from the converter and main thread instead of a single thread. Need to look more into this still.

**Comment by muhku** [comment]
I think the real solution is that we don't queue the converted audio packets in Audio_Queue. I will go for a  simpler solution that Audio_Queue will block the converter thread if it has no free buffers.

**Comment by rfoa** [comment]
I have little knowledge about Decoders, but analyzing the logs I noticed that packages are "discarded" randomly during handling, not reaching the destination (decoder/converter). Consequently, the player is muted.
I also had a suspicion that there would be some "unsynchronization" between Audio_Queue and Audio_Stream.
* These observations are related to what you wrote above?
* Why did the error does not happen in the emulator?

**Comment by muhku** [comment]
Yes, your observations pretty much nail the situation. The packets are now directly consumed without queuing (commit e0e2d9e74c4bb80750dd2755f9cb30357350fe7e). Unit tests pass and overall this is looking like a better solution.

**Comment by rfoa** [comment]
Good news! The 3.0.10 version works correctly.
No muted player. No memory leak.
* What was the main reason for this series of problems?

I will check if there are other related bugs
Thank you!

**Comment by rfoa** [comment]
I noticed another bug: when there is an interruption in the Internet connection, the player plays the old cache stored rather than mute the audio.
At this time I get kFsAudioStreamBuffering the onStateChange, but the player is still playing the cache stored to the end (about 30 seconds).
The attempt to reconnect (kFsAudioStreamRetryingStarted) is performed only after the cache to be consumed.
* In short: The player is playing audio cached (repeating audio that has been previously played) when there is an interruption in the Internet connection
* I think when the player is unable to obtain new packages, the old packets stored in the cache are played again
* I made markings on the log showing the important events

Full Log: [log_player_error_cache.txt](https://github.com/muhku/FreeStreamer/files/57231/log_player_error_cache.txt)

Thanks again

**Comment by muhku** [comment]
Hmm. I think I need a way to reproduce this one. Anyhow, I added an optimization that I have been thinking before: the caches are now cleaned for continuous streams right after the decoder has finished playing up a packet (commit 82e4f31ab20b78ca4a679d2fb016bf1414e06131). This should at least ensure that there is no lingering data around. Does it help?

**Comment by rfoa** [comment]
Yes! The problem has been fixed. Very good.
Now it is working properly.

I noticed that sometimes drops the connection to the radio when connected by wifi, always between 660-900 seconds, but I could not reproduce logs for testing. May be my connection ... I will test on another network.

Thanks for everything

**Comment by muhku** [comment]
Excellent. Thanks for your testing help, too. Just for the record: the regressions happened in 3.0.0 because in Issue #218 it was pointed out that for a visualizer use case it was difficult or impossible to get enough samples. The new decoder implementation in 3.x gives enough samples for this use case. Unfortunately regressions happened as well with the new decoder implementation.

Now that 3.0.11 seems reasonably stable, let's close this one and continue hunt for new bugs in new issues :)
