### ISSUE TITLE
when I Fast switching music it crash

### ISSUE THREAD

**Issue by gaohengwei** [muhku/FreeStreamer#320]
![crash2](https://cloud.githubusercontent.com/assets/16328779/20958707/e8a04cb2-bc91-11e6-923a-f5381222f72e.png)
![crash1](https://cloud.githubusercontent.com/assets/16328779/20958716/f78ab992-bc91-11e6-822f-613f4fa33052.png)

**Comment by muhku** [comment]
Thank you for reporting!
Commit f03be2e4450b3a9e8fa4bbbcefa2ec43b929bb93 introduced crashing due to lacking mutex in the state get/set. Fixed in 99e2d44634b9a4e32d1c784da6018eed762769d4

**Comment by rickyjwhong** [comment]
Hey there,

wonderful library, thanks for putting it out. i think this issue is still there with the mutex lock.

![image](https://cloud.githubusercontent.com/assets/1673456/21005490/e1caa0c4-bce9-11e6-8f99-983cea99fc8e.png)

**Comment by muhku** [comment]
Thanks. It seems currentState() can access deallocated audio queue instance and it crashes. Explanation in #322
